name: Test CI-CD

on:
  push:
    # paths:
    #   - "./server/**"
    # paths-ignore:
    #   - "**/__test__/**"
    branches:
      - main

env:
  S3_BUCKET_NAME: dwitter-codes/codes

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Set up Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: v17.4.0
      #     cache: "npm"

      - name: Install Dependencies
        run: npm i
        working-directory: "./server"

      - name: Compile Typescript
        run: npx tsc
        working-directory: "./server"

      - name: Make zip file
        # run: zip -r intoTheS3.zip ./server/dist/
        run: zip -r $GITHUB_SHA.zip ./server/dist
        # working-directory: "./server"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 $GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip
        # run: aws s3 cp --region ap-northeast-2 $GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip
