name: Test CI-CD

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: dwitter-codes/codes
  DIRECTORY: ./server
  REGION: ap-northeast-2

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: v17.4.0
          cache: "npm"
          cache-dependency-path: ./server/package-lock.json

      - name: Install dependencies
        working-directory: ${{ env.DIRECTORY }}
        run: npm i

      - name: Create .env.test file
        working-directory: ${{ env.DIRECTORY }}
        run: touch .env
          cat << EOF >> .env.test
          PORT = 3000
          HERE = seoul
          EOF

      - name: Compile typescript and test env
        working-directory: ${{ env.DIRECTORY }}
        run: npm test

      # - name: Test Connection
      #   id: test_connect
      #   run: node ./server/dist/index.js
      #   env:
      # HOST: ${{ secrets.HOST }}
      # USERNAME: ${{ secrets.USERNAME }}
      # DATABASE: ${{ secrets.DATABASE }}
      # PASSWORD: ${{ secrets.PASSWORD }}
      # PORT: ${{ secrets.PORT }}

      # - name: If Connection Pass or Fail
      #   if: ${{ success() }}
      #   run: exit 0

      # - name: Make zip file
      #   run: zip -r $GITHUB_SHA.zip ./server/dist -x **/__test__/**

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.REGION }}

      # - name: Upload to S3
      #   run: aws s3 cp --region $REGION $GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      # - name: Code Deploy
      #   run: |
      #     aws deploy create-deployment \
      #     --deployment-config-name CodeDeployDefault.AllAtOnce \
      #     --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
      #     --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
      #     --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
